'__doc__', None)
('__module__', 'bpy.types')
('__slots__', ())
('actions', <bpy_collection[0], BlendDataActions>)
('armatures', <bpy_collection[0], BlendDataArmatures>)
('batch_remove', <built-in function batch_remove>)
('bl_rna', <bpy_struct, Struct("BlendData")>)
('brushes', <bpy_collection[31], BlendDataBrushes>)
('cache_files', <bpy_collection[0], BlendDataCacheFiles>)
('cameras', <bpy_collection[2], BlendDataCameras>)
('collections', <bpy_collection[10], BlendDataCollections>)
('curves', <bpy_collection[1], BlendDataCurves>)
('filepath', '/Volumes/_MINDFLOW/3D/Models/Cars/Blender/Porsche GT3 RSR - by Neubi/Models/Porsche_GT3_RSR_Blendswap-bl293-001.blend')
('fonts', <bpy_collection[0], BlendDataFonts>)
('grease_pencils', <bpy_collection[0], BlendDataGreasePencils>)
('images', <bpy_collection[13], BlendDataImages>)
('is_dirty', True)
('is_saved', True)
('lattices', <bpy_collection[0], BlendDataLattices>)
('libraries', <bpy_collection[4], BlendDataLibraries>)
('lightprobes', <bpy_collection[0], BlendDataProbes>)
('lights', <bpy_collection[1], BlendDataLights>)
('linestyles', <bpy_collection[0], BlendDataLineStyles>)
('masks', <bpy_collection[0], BlendDataMasks>)
('materials', <bpy_collection[32], BlendDataMaterials>)
('meshes', <bpy_collection[56], BlendDataMeshes>)
('metaballs', <bpy_collection[0], BlendDataMetaBalls>)
('movieclips', <bpy_collection[0], BlendDataMovieClips>)
('node_groups', <bpy_collection[2], BlendDataNodeTrees>)
('objects', <bpy_collection[62], BlendDataObjects>)
('orphans_purge', <built-in function orphans_purge>)
('paint_curves', <bpy_collection[0], BlendDataPaintCurves>)
('palettes', <bpy_collection[0], BlendDataPalettes>)
('particles', <bpy_collection[0], BlendDataParticles>)
('rna_type', <bpy_struct, Struct("BlendData")>)
('scenes', <bpy_collection[1], BlendDataScenes>)
('screens', <bpy_collection[17], BlendDataScreens>)
('shape_keys', <bpy_collection[0], BlendData.shape_keys>)
('sounds', <bpy_collection[0], BlendDataSounds>)
('speakers', <bpy_collection[0], BlendDataSpeakers>)
('texts', <bpy_collection[16], BlendDataTexts>)
('textures', <bpy_collection[0], BlendDataTextures>)
('use_autopack', False)
('user_map', <built-in function user_map>)
('version', (2, 93, 21))
('volumes', <bpy_collection[0], BlendDataVolumes>)
('window_managers', <bpy_collection[1], BlendDataWindowManagers>)
('workspaces', <bpy_collection[10], BlendDataWorkSpaces>)
('worlds', <bpy_collection[1], BlendDataWorlds>)

